version: "3.6"

services:
  sut:
    build: .
    volumes:
      - lidarr_config:/config
    command: >
      bash -c "/opt/lidarr/bin/Lidarr -nobrowser -data=/config & \
               test.sh -t 30 -u http://localhost:8686/ -e Lidarr"

volumes:
  lidarr_config:
    driver_opts:
      type: tmpfs
      device: tmpfs
